// Renders a review result to a Markdown conditions brief for download / print.

import type { ReviewResult } from "./types";

export function renderBriefMarkdown(result: ReviewResult): string {
  const { evidence: e, brief: b } = result;
  const lines: string[] = [];

  lines.push(`# Tanseeq Conditions Brief / موجز التنسيق`);
  lines.push("");
  lines.push(`> Advisory conditions brief for a human review committee. Not a regulatory approval.`);
  lines.push("");
  lines.push(`- **Case file:** ${e.caseFileId}`);
  lines.push(`- **Parcel:** ${e.parcel.parcel_id} (${e.parcel.current_status.replace(/_/g, " ")})`);
  lines.push(`- **District:** ${e.parcel.district}`);
  lines.push(`- **Proposed use:** ${e.proposedUseLabel}`);
  lines.push(`- **Decision readiness:** ${b.decisionLabel}`);
  lines.push(`- **Generated by:** ${b.generatedBy}`);
  lines.push("");

  lines.push(`## Coordination`);
  lines.push(`- Development pressure: **${e.pressure.developmentPressure}/100**`);
  lines.push(`- Community absorption: **${e.pressure.communityAbsorption}/100**`);
  lines.push(`- Coordination divergence: **${e.pressure.coordinationDivergence}**`);
  lines.push("");

  lines.push(`## Committee summary`);
  lines.push(b.committeeSummary);
  lines.push("");
  lines.push(`## Why not as submitted`);
  lines.push(b.whyNotAsSubmitted);
  lines.push("");

  lines.push(`## Five coordination checks`);
  for (const c of e.checks) {
    lines.push(`### ${c.title} — ${c.score}/100 (${c.status})`);
    lines.push(c.finding);
    lines.push("");
    for (const ev of c.evidence) lines.push(`- ${ev}`);
    lines.push(`- _Risk:_ ${c.risk}`);
    lines.push(`- _Recommendation:_ ${c.recommendation}`);
    lines.push(`- _Fields used:_ ${c.fieldsUsed.join(", ")}`);
    lines.push("");
  }

  lines.push(`## Required conditions for review`);
  for (const cond of b.requiredConditions) lines.push(`- ${cond}`);
  lines.push("");

  lines.push(`## Evidence references`);
  for (const ref of b.evidenceReferences) lines.push(`- ${ref}`);
  lines.push("");

  lines.push(`## Questions for human review`);
  for (const q of b.questionsForHumanReview) lines.push(`- ${q}`);
  lines.push("");

  lines.push(`## Limitations`);
  for (const l of b.limitations) lines.push(`- ${l}`);
  lines.push("");

  lines.push(`---`);
  lines.push(
    `Challenge sample datasets are synthetic and used for prototype scoring. OSM amenities are real OpenStreetMap data © OpenStreetMap contributors (ODbL).`,
  );

  return lines.join("\n");
}
