import type { DevelopmentProposal, Verdict } from "./types";

export const blankProposal: DevelopmentProposal = {
  projectName: "",
  applicant: "",
  parcelId: "",
  locality: "",
  zoneCode: "R2",
  proposedUse: "residential",
  plotAreaSqm: 0,
  grossFloorAreaSqm: 0,
  buildingFootprintSqm: 0,
  buildingHeightM: 0,
  storeys: 0,
  dwellingUnits: 0,
  parkingSpaces: 0,
  frontSetbackM: 0,
  sideSetbackM: 0,
  rearSetbackM: 0,
  landscapeAreaSqm: 0,
  greenRating: 0,
  hasLegalAccess: true,
  utilities: { water: "available", power: "available", sewer: "available", stormwater: "available" },
  siteConstraints: { floodZone: false, heritageOverlay: false, contaminationRisk: false },
  estimatedJobs: 0,
  notes: "",
};

export interface Preset {
  id: string;
  label: string;
  expectedVerdict: Verdict;
  blurb: string;
  proposal: DevelopmentProposal;
}

export const PRESETS: Preset[] = [
  {
    id: "compliant-residential",
    label: "Al Noor Residences",
    expectedVerdict: "Proceed",
    blurb: "Compliant medium-density apartments — fully within the development envelope.",
    proposal: {
      projectName: "Al Noor Residences",
      applicant: "Meridian Living Developments",
      parcelId: "PLT-2207-R2",
      locality: "Khalidiya District",
      zoneCode: "R2",
      proposedUse: "residential",
      plotAreaSqm: 4000,
      grossFloorAreaSqm: 6800,
      buildingFootprintSqm: 1800,
      buildingHeightM: 22,
      storeys: 6,
      dwellingUnits: 40,
      parkingSpaces: 64,
      frontSetbackM: 6,
      sideSetbackM: 4,
      rearSetbackM: 5,
      landscapeAreaSqm: 1100,
      greenRating: 3,
      hasLegalAccess: true,
      utilities: { water: "available", power: "available", sewer: "available", stormwater: "available" },
      siteConstraints: { floodZone: false, heritageOverlay: false, contaminationRisk: false },
      estimatedJobs: 12,
      notes: "Two L-shaped blocks around a landscaped courtyard; basement parking.",
    },
  },
  {
    id: "conditions-tower",
    label: "Marsa Heights Tower",
    expectedVerdict: "Approve with Conditions",
    blurb: "High-density tower with minor exceedances resolvable by condition.",
    proposal: {
      projectName: "Marsa Heights Tower",
      applicant: "Skyline Urban Partners",
      parcelId: "PLT-1184-R3",
      locality: "Marina Waterfront",
      zoneCode: "R3",
      proposedUse: "residential",
      plotAreaSqm: 6000,
      grossFloorAreaSqm: 22000,
      buildingFootprintSqm: 3400,
      buildingHeightM: 58,
      storeys: 18,
      dwellingUnits: 180,
      parkingSpaces: 210,
      frontSetbackM: 4,
      sideSetbackM: 3.5,
      rearSetbackM: 5,
      landscapeAreaSqm: 1100,
      greenRating: 2,
      hasLegalAccess: true,
      utilities: { water: "available", power: "available", sewer: "available", stormwater: "planned" },
      siteConstraints: { floodZone: false, heritageOverlay: true, contaminationRisk: false },
      estimatedJobs: 40,
      notes: "Single tower on a 3-storey podium adjacent to a listed warehouse frontage.",
    },
  },
  {
    id: "rescope-commercial",
    label: "Gateway Commercial Centre",
    expectedVerdict: "Re-scope",
    blurb: "Office scheme that materially over-develops the plot — must be revised.",
    proposal: {
      projectName: "Gateway Commercial Centre",
      applicant: "Anchor Capital Real Estate",
      parcelId: "PLT-0492-C1",
      locality: "Central Business Spine",
      zoneCode: "C1",
      proposedUse: "commercial",
      plotAreaSqm: 5000,
      grossFloorAreaSqm: 21000,
      buildingFootprintSqm: 3600,
      buildingHeightM: 60,
      storeys: 16,
      dwellingUnits: 0,
      parkingSpaces: 300,
      frontSetbackM: 3,
      sideSetbackM: 1,
      rearSetbackM: 3,
      landscapeAreaSqm: 700,
      greenRating: 3,
      hasLegalAccess: true,
      utilities: { water: "available", power: "available", sewer: "available", stormwater: "available" },
      siteConstraints: { floodZone: false, heritageOverlay: false, contaminationRisk: false },
      estimatedJobs: 900,
      notes: "Twin-core office block with retail podium; applicant seeks maximum lettable area.",
    },
  },
  {
    id: "hold-industrial",
    label: "Falcon Logistics Depot",
    expectedVerdict: "Hold",
    blurb: "Industrial use in a residential zone with no access and contamination — fundamental impediments.",
    proposal: {
      projectName: "Falcon Logistics Depot",
      applicant: "Falcon Freight Holdings",
      parcelId: "PLT-3320-R1",
      locality: "Green Belt Fringe",
      zoneCode: "R1",
      proposedUse: "industrial",
      plotAreaSqm: 3000,
      grossFloorAreaSqm: 2000,
      buildingFootprintSqm: 1100,
      buildingHeightM: 9,
      storeys: 2,
      dwellingUnits: 0,
      parkingSpaces: 40,
      frontSetbackM: 8,
      sideSetbackM: 5,
      rearSetbackM: 5,
      landscapeAreaSqm: 1050,
      greenRating: 2,
      hasLegalAccess: false,
      utilities: { water: "absent", power: "available", sewer: "available", stormwater: "available" },
      siteConstraints: { floodZone: false, heritageOverlay: false, contaminationRisk: true },
      estimatedJobs: 60,
      notes: "Distribution warehouse proposed on a low-density residential parcel with no road frontage.",
    },
  },
];

export function getPreset(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}
