import type { ZoneCode, ZoneRegulation } from "./types";

/**
 * Development control regulations per zone. Values are illustrative of a
 * typical municipal planning code and drive every assessment in the engine.
 */
export const ZONE_REGULATIONS: Record<ZoneCode, ZoneRegulation> = {
  R1: {
    code: "R1",
    name: "R1 — Low-density Residential",
    summary: "Detached and low-rise dwellings on generous plots.",
    permittedUses: ["residential", "community"],
    maxPlotRatio: 0.8,
    maxHeightM: 12,
    maxStoreys: 3,
    maxSiteCoverPct: 40,
    minFrontSetbackM: 6,
    minSideSetbackM: 3,
    minRearSetbackM: 3,
    minLandscapePct: 35,
    minParkingPerUnit: 2,
    parkingPer100SqmGfa: 0,
    maxDensityUnitsPerHa: 35,
    minGreenRating: 2,
  },
  R2: {
    code: "R2",
    name: "R2 — Medium-density Residential",
    summary: "Townhouses and low-to-mid-rise apartments.",
    permittedUses: ["residential", "community"],
    maxPlotRatio: 1.8,
    maxHeightM: 24,
    maxStoreys: 7,
    maxSiteCoverPct: 50,
    minFrontSetbackM: 5,
    minSideSetbackM: 3,
    minRearSetbackM: 4,
    minLandscapePct: 25,
    minParkingPerUnit: 1.5,
    parkingPer100SqmGfa: 0,
    maxDensityUnitsPerHa: 120,
    minGreenRating: 2,
  },
  R3: {
    code: "R3",
    name: "R3 — High-density Residential",
    summary: "Mid- and high-rise apartment buildings.",
    permittedUses: ["residential", "community", "mixed_use"],
    maxPlotRatio: 3.5,
    maxHeightM: 60,
    maxStoreys: 18,
    maxSiteCoverPct: 55,
    minFrontSetbackM: 4,
    minSideSetbackM: 4,
    minRearSetbackM: 5,
    minLandscapePct: 20,
    minParkingPerUnit: 1.25,
    parkingPer100SqmGfa: 1,
    maxDensityUnitsPerHa: 350,
    minGreenRating: 3,
  },
  C1: {
    code: "C1",
    name: "C1 — Commercial / Retail",
    summary: "Offices, retail and service commercial premises.",
    permittedUses: ["commercial", "mixed_use", "community"],
    maxPlotRatio: 3.0,
    maxHeightM: 45,
    maxStoreys: 12,
    maxSiteCoverPct: 70,
    minFrontSetbackM: 3,
    minSideSetbackM: 0,
    minRearSetbackM: 3,
    minLandscapePct: 12,
    minParkingPerUnit: 0,
    parkingPer100SqmGfa: 2.5,
    maxDensityUnitsPerHa: 0,
    minGreenRating: 3,
  },
  MU: {
    code: "MU",
    name: "MU — Mixed-use",
    summary: "Integrated residential, retail and workplace development.",
    permittedUses: ["mixed_use", "residential", "commercial", "hospitality", "community"],
    maxPlotRatio: 4.0,
    maxHeightM: 75,
    maxStoreys: 22,
    maxSiteCoverPct: 65,
    minFrontSetbackM: 3,
    minSideSetbackM: 3,
    minRearSetbackM: 4,
    minLandscapePct: 15,
    minParkingPerUnit: 1,
    parkingPer100SqmGfa: 1.5,
    maxDensityUnitsPerHa: 400,
    minGreenRating: 3,
  },
  IND: {
    code: "IND",
    name: "IND — Light Industrial / Logistics",
    summary: "Warehousing, light manufacturing and logistics.",
    permittedUses: ["industrial", "commercial"],
    maxPlotRatio: 1.5,
    maxHeightM: 18,
    maxStoreys: 4,
    maxSiteCoverPct: 60,
    minFrontSetbackM: 8,
    minSideSetbackM: 5,
    minRearSetbackM: 5,
    minLandscapePct: 12,
    minParkingPerUnit: 0,
    parkingPer100SqmGfa: 1,
    maxDensityUnitsPerHa: 0,
    minGreenRating: 2,
  },
  HOS: {
    code: "HOS",
    name: "HOS — Hospitality / Tourism",
    summary: "Hotels, resorts and serviced apartments.",
    permittedUses: ["hospitality", "mixed_use", "commercial"],
    maxPlotRatio: 3.2,
    maxHeightM: 55,
    maxStoreys: 15,
    maxSiteCoverPct: 55,
    minFrontSetbackM: 5,
    minSideSetbackM: 4,
    minRearSetbackM: 5,
    minLandscapePct: 25,
    minParkingPerUnit: 0,
    parkingPer100SqmGfa: 1.2,
    maxDensityUnitsPerHa: 0,
    minGreenRating: 4,
  },
};

export function getRegulation(code: ZoneCode): ZoneRegulation {
  return ZONE_REGULATIONS[code];
}

export const ZONE_OPTIONS: ZoneCode[] = ["R1", "R2", "R3", "C1", "MU", "IND", "HOS"];
