"use client";

import type { ReviewResult } from "@/lib/tanseeq/types";
import { DECISION_AR, DECISION_STYLE } from "./ui";

export default function ConditionsBrief({ result }: { result: ReviewResult }) {
  const { evidence: e, brief: b } = result;
  const ds = DECISION_STYLE[b.decisionLabel];

  return (
    <div className="print-full rounded-2xl border border-room-line bg-room-panel p-5">
      {/* Title */}
      <div className="flex items-start justify-between gap-3 border-b border-room-line pb-4">
        <div>
          <h3 className="text-base font-bold text-room-ink">
            Tanseeq Conditions Brief <span className="font-normal text-room-muted">/ موجز التنسيق</span>
          </h3>
          <p className="mt-0.5 font-mono text-[11px] text-teal">{e.caseFileId}</p>
        </div>
        <span
          className={`shrink-0 inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-semibold ${ds.chip}`}
        >
          <span className={`h-2 w-2 rounded-full ${ds.dot}`} />
          {b.decisionLabel}
        </span>
      </div>

      {/* Case meta */}
      <div className="mt-3 grid grid-cols-2 gap-2 text-[12px] sm:grid-cols-4">
        <Meta label="Parcel" value={e.parcel.parcel_id} />
        <Meta label="District" value={e.parcel.district} />
        <Meta label="Proposed use" value={e.proposedUseLabel} />
        <Meta label="Generated by" value={b.generatedBy} />
      </div>

      <p className="mt-3 text-[11px] text-room-muted" dir="rtl">
        جاهزية القرار — {DECISION_AR[b.decisionLabel]}
      </p>

      <Section title="Committee summary" titleAr="ملخص اللجنة">
        <p className="text-[13px] leading-relaxed text-room-ink/90">{b.committeeSummary}</p>
      </Section>

      <Section title="Why not as submitted" titleAr="لماذا ليس كما هو مقدم">
        <p className="text-[13px] leading-relaxed text-room-ink/90">{b.whyNotAsSubmitted}</p>
      </Section>

      <Section title="Required conditions" titleAr="شروط للمراجعة">
        <ul className="space-y-1.5">
          {b.requiredConditions.map((c, i) => (
            <li key={i} className="flex gap-2 text-[13px] text-room-ink/90">
              <span className="mt-0.5 text-gold">◆</span>
              <span>{c}</span>
            </li>
          ))}
        </ul>
      </Section>

      <Section title="Evidence references" titleAr="مراجع الأدلة">
        <ul className="space-y-1">
          {b.evidenceReferences.map((c, i) => (
            <li key={i} className="flex gap-2 text-[12px] text-room-muted">
              <span className="text-teal">▸</span>
              <span>{c}</span>
            </li>
          ))}
        </ul>
      </Section>

      <Section title="Questions for human review" titleAr="أسئلة للمراجعة البشرية">
        <ul className="space-y-1.5">
          {b.questionsForHumanReview.map((c, i) => (
            <li key={i} className="flex gap-2 text-[13px] text-room-ink/90">
              <span className="mt-0.5 text-room-muted">?</span>
              <span>{c}</span>
            </li>
          ))}
        </ul>
      </Section>

      <Section title="Limitations" titleAr="القيود">
        <ul className="space-y-1">
          {b.limitations.map((c, i) => (
            <li key={i} className="text-[11px] leading-snug text-room-muted">
              · {c}
            </li>
          ))}
        </ul>
      </Section>

      <div className="mt-4 rounded-lg border border-room-line bg-room-bg/50 px-3 py-2 text-[10px] leading-snug text-room-muted">
        Challenge sample datasets are synthetic and used for prototype scoring. OSM amenities are real
        OpenStreetMap data © OpenStreetMap contributors (ODbL). Tanseeq is advisory and does not grant
        statutory consent or approval.
      </div>
    </div>
  );
}

function Meta({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-room-line bg-room-bg/40 px-2.5 py-1.5">
      <div className="text-[10px] uppercase tracking-wide text-room-muted">{label}</div>
      <div className="truncate text-[13px] font-medium capitalize text-room-ink">{value}</div>
    </div>
  );
}

function Section({
  title,
  titleAr,
  children,
}: {
  title: string;
  titleAr: string;
  children: React.ReactNode;
}) {
  return (
    <div className="mt-4 border-t border-room-line pt-3">
      <div className="mb-2 flex items-baseline justify-between">
        <h4 className="text-[11px] font-semibold uppercase tracking-wider text-teal">{title}</h4>
        <span className="text-[11px] text-room-muted" dir="rtl">
          {titleAr}
        </span>
      </div>
      {children}
    </div>
  );
}
